version: '3.8'

services:

  traefik:
    image: 'traefik:latest'
    #image: 'traefik:v2.4.8'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
      - '/run/homelab/storage/traefik/traefik.toml:/traefik.toml'
      - '/run/homelab/storage/traefik/config:/config'
    networks: [swarm]
    deploy:
      mode: replicated
      replicas: 1
      labels:
        # serve traefik on https://monitor.homelab.express
        - 'traefik.enable=true'
        - 'traefik.http.routers.traefik.rule=Host(`monitor.homelab.express`)'
        - 'traefik.http.routers.traefik.service=api@internal'
        - 'traefik.http.routers.traefik.entrypoints=web-secure'
        - 'traefik.http.routers.traefik.tls'
        - 'traefik.http.services.traefik.loadbalancer.server.port=8080'
        # global redirect to https (permanent)
        - 'traefik.http.middlewares.scheme-redirect.redirectscheme.scheme=https'
        - 'traefik.http.middlewares.scheme-redirect.redirectscheme.permanent=true'
        - 'traefik.http.routers.scheme-redirect.rule=hostregexp(`{host:.+}`)'
        - 'traefik.http.routers.scheme-redirect.entrypoints=web'
        - 'traefik.http.routers.scheme-redirect.middlewares=scheme-redirect'

  traefik-cert-updater:
    image: 'cinderblockgames/homelab.express-cert-updater:latest'
    #image: 'cinderblockgames/homelab.express-cert-updater:v1.0.0'
    volumes:
      - '/run/homelab/storage/traefik/config/certs.toml:/data/dynamic.toml'
      - '/run/homelab/storage/traefik/config/certs:/data/certs'
    networks: [swarm]
    deploy:
      mode: replicated
      replicas: 1

  portainer-agent:
    image: 'portainer/agent'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/var/lib/docker/volumes:/var/lib/docker/volumes'
    ports: ['9001:9001']
    networks: [swarm]
    deploy:
      mode: global

  portainer:
    image: 'portainer/portainer-ce:linux-arm'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/run/homelab/storage/portainer:/data'
    networks: [swarm]
    deploy:
      mode: replicated
      replicas: 1
      #placement:
      #  constraints: [node.platform.arch == armv7l]
      labels:
        - 'traefik.enable=true'
        - 'traefik.http.routers.portainer.rule=Host(`manage.homelab.express`)'
        - 'traefik.http.routers.portainer.entrypoints=web-secure'
        - 'traefik.http.routers.portainer.tls'
        - 'traefik.http.services.portainer.loadbalancer.server.port=9000'

networks:
  swarm:
    external: true
