version: '3.8'

services:
  traefik:
    image: 'traefik:latest'
    #image: 'traefik:v2.4.8'
    container_name: 'traefik'
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
      - '/run/homelab/storage/traefik/traefik.toml:/traefik.toml'
      - '/run/homelab/storage/traefik/config:/config'
    network_mode: bridge
    labels:
      # serve traefik on https://${hostname}.homelab.express
      - 'traefik.enable=true'
      - 'traefik.http.routers.traefik.rule=Host(`${hostname}.homelab.express`)'
      - 'traefik.http.routers.traefik.service=api@internal'
      - 'traefik.http.routers.traefik.entrypoints=web-secure'
      - 'traefik.http.routers.traefik.tls'
      - 'traefik.http.services.traefik.loadbalancer.server.port=8080'
      # global redirect to https (permanent)
      - 'traefik.http.middlewares.scheme-redirect.redirectscheme.scheme=https'
      - 'traefik.http.middlewares.scheme-redirect.redirectscheme.permanent=true'
      - 'traefik.http.routers.scheme-redirect.rule=hostregexp(`{host:.+}`)'
      - 'traefik.http.routers.scheme-redirect.entrypoints=web'
      - 'traefik.http.routers.scheme-redirect.middlewares=scheme-redirect'

  traefik-cert-updater:
    image: 'cinderblockgames/homelab.express-cert-updater:latest'
    #image: 'cinderblockgames/homelab.express-cert-updater:v1.0.0'
    #build: 'https://github.com/cinderblockgames/homelab.express-cert-updater.git#main'
    container_name: 'traefik-cert-updater'
    restart: always
    volumes:
      - '/run/homelab/storage/traefik/config/certs.toml:/data/dynamic.toml'
      - '/run/homelab/storage/traefik/config/certs:/data/certs'
    network_mode: bridge

  portainer-agent:
    image: 'portainer/agent'
    container_name: 'portainer-agent'
    restart: always
    ports:
      - '9001:9001'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/var/lib/docker/volumes:/var/lib/docker/volumes'
    network_mode: bridge
