name: Update Certificate

# Controls when the action will run.
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  update-cert:
    runs-on: ubuntu-latest
    steps:
      - name: Copy ACME account key
        uses: DamianReeves/write-file-action@v1.0
        with:
          path: keys/acme.key
          contents: ${{ secrets.ACME_ACCOUNT_KEY }}
          write-mode: overwrite
      - name: Issue certificate
        uses: cinderblockgames/letsencrypt-dns-cpanel-action@develop
        with:
          # cPanel
          host: cinderblockgames.com
          cpanelUsername: '${{ secrets.CPANEL_USERNAME }}'
          cpanelApiToken: '${{ secrets.CPANEL_API_KEY }}'
          domain: homelab.express
          # Let's Encrypt
          acmeAccountEmailAddress: hello@cinderblockgames.com
          acmeAccountKey: keys/acme.key
          certCN: '*.homelab.express'
          certOrg: homelab.express
          certOU: private network
          certLocality: private
          certState: network
          certCountry: earth
          certDomainList: '*.homelab.express|*.macademia.homelab.express|*.chestnut.homelab.express'
          # GitHub
          githubAccessToken: '${{ secrets.GIT_HUB_ACCESS_TOKEN }}'
          secretsRepo: cinderblockgames/homelab.express
          
          #secrets
          acmeAccountKeyName: ACME_ACCOUNT_KEY_2
          publicChainName: CERT_PUBLIC_CHAIN_2
          privateKeyName: CERT_PRIVATE_KEY_2
