name: Revoke Certificate

# Controls when the action will run.
on:
  # Run after the cert has been created
  workflow_run:
    workflows: ["Update Certificate"]
    types: ["completed"]
      
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  revoke-cert:
    runs-on: ubuntu-latest
    steps:
      - name: Copy ACME account key
        uses: DamianReeves/write-file-action@v1.0
        with:
          path: 'secrets/acme.key'
          contents: ${{ secrets.ACME_ACCOUNT_KEY_2 }}
          write-mode: overwrite
      - name: Copy certificate chain
        uses: DamianReeves/write-file-action@v1.0
        with:
          path: 'secrets/cert.cer'
          contents: ${{ secrets.CERT_PUBLIC_CHAIN_2 }}
          write-mode: overwrite
      - name: Copy certificate private key
        uses: kitek/decode-base64-into-file-action@1.0
        with:
          encoded-value: ${{ secrets.CERT_PRIVATE_KEY_2 }}
          destination-file: secrets/cert.pfx
      - name: Remove private key protection
        run: openssl pkcs12 -in ${{ github.workspace }}/secrets/cert.pfx -nocerts -out ${{ github.workspace }}/secrets/cert.key -nodes -password pass:''
      - name: Revoke certificate
        uses: cinderblockgames/letsencrypt-revoke-action@develop
        with:
          # REQUIRED
          certChainPath: 'secrets/cert.cer'
          #acmeAccountKeyPath: 'secrets/acme.key'
          certKeyPath: 'secrets/cert.key'
          reason: 'KeyCompromise'
