name: Revoke Certificate

# Controls when the action will run.
on:
  # Run after the cert has been created
  workflow_run:
    workflows: ["Update Certificate"]
    types: ["completed"]
      
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  revoke-cert:
    runs-on: ubuntu-latest
    container: certbot/certbot
    steps:
      - name: Copy certificate public chain
        uses: DamianReeves/write-file-action@v1.0
        with:
          path: cert/wildcard.homelab.express.cer
          contents: ${{ secrets.CERT_PUBLIC_CHAIN }}
          write-mode: overwrite
      - name: Copy certificate private key
        uses: kitek/decode-base64-into-file-action@1.0
        with:
          encoded-value: ${{ secrets.CERT_PRIVATE_KEY }}
          destination-file: cert/wildcard.homelab.express.pfx
      - name: Remove private key protection
        run: openssl pkcs12 -in cert/wildcard.homelab.express.pfx -nocerts -out cert/wildcard.homelab.express.key -nodes -password pass:''
      - name: Revoke certificate
        run: certbot revoke --cert-path cert/wildcard.homelab.express.cer --key-path cert/wildcard.homelab.express.key
      - name: read logs
        run: cat /var/log/letsencrypt/letsencrypt.log
        if: always()
