name: Upload Certificate

# Controls when the action will run.
on:
  # Run after the cert has been created
  workflow_run:
    workflows: ["Issue Certificate"]
    types: ["completed"]
      
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  upload-cert:
    runs-on: ubuntu-latest
    steps:
      - name: Copy certificate public chain
        uses: DamianReeves/write-file-action@v1.0
        with:
          path: web/cert/wildcard.homelab.express.cer
          contents: ${{ secrets.CERT_PUBLIC_CHAIN }}
          write-mode: overwrite
      - name: Copy certificate private key
        uses: kitek/decode-base64-into-file-action@1.0
        with:
          encoded-value: ${{ secrets.CERT_PRIVATE_KEY }}
          destination-file: web/cert/wildcard.homelab.express.pfx
      - name: Remove private key protection
        run: openssl pkcs12 -in ${{ github.workspace }}/web/cert/wildcard.homelab.express.pfx -nocerts -out ${{ github.workspace }}/web/cert/wildcard.homelab.express.key -nodes -password pass:''
      - name: Copy to server
        uses: cinderblockgames/ftp-action@v1.2.2
        with:
          # required
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          # optional
          source: web/cert/
          destination: cert/
          skipUnchanged: true
      - name: Commit files
        id: commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "github-actions"
          git add --all
          if [-z "$(git status --porcelain)"]; then
             echo "::set-output name=push::false"
          else
             git commit -m "Add changes" -a
             echo "::set-output name=push::true"
          fi
        shell: bash
      - name: Push changes
        if: steps.commit.outputs.push == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
