name: View ACME_ACCOUNT_KEY

# Controls when the action will run.
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  upload-cert:
    runs-on: ubuntu-latest
    steps:
      - uses: DamianReeves/write-file-action@v1.0
        with:
          path: out/key.1
          contents: ${{ secrets.ACME_ACCOUNT_KEY }}
          write-mode: overwrite
      - uses: kitek/decode-base64-into-file-action@1.0
        with:
          encoded-value: ${{ secrets.ACME_ACCOUNT_KEY }}
          destination-file: out/key.2
      - uses: cinderblockgames/ftp-action@v1.2.2
        with:
          # required
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          # optional
          source: out/
          destination: out/
          skipUnchanged: false
